baseURL      = 'https://chronically.blog/'
languageCode = 'en-us'
title        = 'Chronically'
theme        = 'stack'

defaultContentLanguage = 'en'

hasCJKLanguage = false

[pagination]
    pagerSize = 5

[caches]
  [caches.images]
    dir = ':cacheDir/images'