# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true

[footer]
    since = 2025

[dateFormat]
    published   = "Jan 02, 2006"
    lastUpdated = "Jan 02, 2006 15:04 EST"

[sidebar]
    subtitle = "The rambling a girl who is chronically online and chronically ill."

[sidebar.avatar]
    enabled = true
    local   = true
    src     = "images/avatar.jpg"

[article]
    headingAnchor = false
    math          = false
    readingTime   = true

## Widgets
[[widgets.homepage]]
    type = "search"

[[widgets.homepage]]
    type = "archives"

[widgets.homepage.params]
    limit = 5

[[widgets.homepage]]
    type = "categories"

[widgets.homepage.params]
    limit = 10

[[widgets.homepage]]
    type = "tag-cloud"

[widgets.homepage.params]
    limit = 10

[[widgets.page]]
    type = "toc"

[colorScheme]
    toggle  = true
    default = "auto"

[imageProcessing.cover]
    enabled = true

[imageProcessing.content]
    enabled = true

## Comments
[comments]
    enabled = false
